# 'make' is one application program to realize special functionalities
# 'makefile' works to translate scripts, and defines the object, as well as orders to implement the objects

### Try the following cmd ###
# make
# make -f <filename> hello
# make hello
# make test



hello : 
	echo "hello makefile"

test: 
	echo "test"
	pwd
	ls
	
